# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c08ea287ef03dcf7488a7913b6897950f32acd29bf5471527d14f31118fe92135ee383ada582c404895b6823c748f8d6db2a7bf2461ec7f1e7594b4610c0d5da

test:
  secret_key_base: 016de3a5635e88885d20645f100f48af58fb65bce35b848bbb68f70938708d249185d30ce67a8084f966c61698c84ac49a42ce0f297c8b988c3f7c2c2adb5acf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
